spring:
    application:
        name: backend_asset
server:
    port: 8082

service:
  api:
    url: http://localhost:8080
  product:
    url: http://localhost:8081  # TODO: Product 서비스 URL 수정
  escrow:
    url: http://localhost:8084  # TODO: Asset 서비스 URL 수정
  market:
    url: http://localhost:8086  # TODO: Asset 서비스 URL 수정

encryption:
  master:
    # 1단계에서 생성한 Base64 인코딩된 키로 교체합니다.
    key: "CppjKe/vlomxodmWvKE4GY2coaxCPm38Aor/DPtni7Y="