server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/asset?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false

  kafka:
    listener:
      ackMode: manual_immediate
    consumer:
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      enableAutoCommit: false
      autoOffsetReset: latest
      maxPollRecords: 10
      properties:
        springJsonTrustedPackages: \"*\"
        springJsonUseTypeHeaders: false

    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        springJsonAddTypeHeaders: false
    bootstrapServers: http://localhost:9092

