apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddiring-backend-asset-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddiring-backend-asset
  template:
    metadata:
      labels:
        app: ddiring-backend-asset
    spec:
      containers:
      - name: ddiring-backend-asset
        image: backend_asset:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8082